### ISSUE TITLE
trouver un format moins flou que les thumbnails gallica pour afficher les résultats de la recherche

### ISSUE THREAD

**Issue by taniki** [hackathonBnF/gallicalol#12]

**Comment by antoinecourtin** [comment]
Tu as le .highres (ex: http://gallica.bnf.fr/ark:/12148/bpt6k96249962/f13.highres) et ensuite pour la partie de memification, tu peux choper la HD en utilisant iiif (tuto https://goo.gl/uno6CW)

**Comment by taniki** [comment]
highres c'est ce qu'on utilise pour la memification mais c'est trop pour les résultats de search (:

**Comment by antoinecourtin** [comment]
ok. A partir des URLs simple, je ne suis pas sur qu'il existe autre chose.
Pour jouer sur la taille, faut passer par iiif car tu peux mettre dans ta requête la taille que tu souhaites (ex: http://gallica.bnf.fr/iiif/ark:/12148/btv1b55001989s/f1/full/250,350/0/native.jpg).
Plus d'info sur la doc http://iiif.io/api/image/2.0/#region

**Comment by taniki** [comment]
merci pour le lien vers la doc. en regardant vite fait, ça sera même possible de spécifier directement les vignettes pour qu'elles aient la taille de ce celles qu'on attent sur le site (:

**Comment by tledoux** [comment]
Sinon entre thumbnail et highres, il y a encore lowres et medres. tu peux consulter la doc sur le wiki https://github.com/hackathonBnF/hackathon2016/wiki/SERVICE-VISU-IMAGE

**Comment by taniki** [comment]
Bon on remarquera que le passage de `thumbnail` à `lowres` rajoute une sorte de watermark
