### ISSUE TITLE
trouver un workflow de deploiement simple

### ISSUE THREAD

**Issue by taniki** [hackathonBnF/gallicalol#9]

**Comment by taniki** [comment]
je crois que ça va se régler à coup de scp/rsync

**Comment by alexsegura** [comment]
Avec Simple Hosting tu peux monter un dossier en local avec SSHFS, je vais voir ça

**Comment by alexsegura** [comment]
Fixé dans d4e7262b701d4a2ab65c7261180e59b11648a3ce
